global using FluentAssertions;
global using Fudie.Security;
global using Fudie.Security.Jwt;
global using Microsoft.Extensions.Configuration;
global using Microsoft.IdentityModel.JsonWebTokens;
global using Microsoft.IdentityModel.Tokens;
global using Moq;
global using System.Security.Cryptography;
global using System.Text.Json;
